### ISSUE TITLE
Add support for symbolic stacktraces in computation expressions

### ISSUE THREAD

**Issue by baronfel** [baronfel/fsharp-lang-suggestions-final#101]
# Add support for symbolic stacktraces in computation expressions [13499082] #

**Submitted by Eirik George Tsarpalis on 4/20/2016 12:00:00 AM**  
**59 votes on UserVoice prior to migration**  

One of the biggest problem in async or computation expressions in general is lack of proper stacktraces when exceptions are raised. This is a major annoyance when debugging in the large, often leading to errors whose origin cannot be traced.
I recently made a blog post arguing for the addition of language features that would make symbolic stacktraces possible for computation expression authors: https://eiriktsarpalis.wordpress.com/2015/12/27/reconciling-stacktraces-with-computation-expressions/
Symbolic stacktraces is a feature that has already appeared in languages like C# (https://github.com/ljw1004/async-exception-stacktrace) and JavaScript (http://www.html5rocks.com/en/tutorials/developertools/async-call-stack/)

## Response ##
** by fslang-admin on 8/2/2016 12:00:00 AM **

See Eirik’s comment below

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/13499082)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-13499082-add-support-for-symbolic-stacktraces-in-computati.md#comments)

**Comment by xperiandri** [comment]
@baronfel does it work as described in the blog post above?

**Comment by bartelink** [comment]
@xperiandri see tail of https://github.com/dotnet/fsharp/issues/2741 for latest state of play
https://eiriktsarpalis.wordpress.com/2016/11/19/reconciling-stacktraces-with-computation-expressions-revisited/
https://gist.github.com/eiriktsarpalis/a97aed20a08bd7b575fda9701209306c
