### ISSUE TITLE
Allow private constructors on DU cases

### ISSUE THREAD

**Issue by baronfel** [baronfel/fsharp-lang-suggestions-final#161]
# Allow private constructors on DU cases [5663374] #

**Submitted by Richard Gibson on 3/21/2014 12:00:00 AM**  
**6 votes on UserVoice prior to migration**  

Currently we can use DUs to represent several possible states. So if I want to I can have:
type EmailAddress =
| ValidEmail of string
| InvalidEmail of string with
static member Create email =
if Regex(".+@.+\..+").IsMatch email
then ValidEmail email
else InvalidEmail email

But the problem with this is that anyone can create either of my cases. There's nothing to stop someone calling one of the constructors directly like so:

let email = ValidEmail "wubwubwub"
I would like to be able to "hide" the constructors for the individual cases and have a constructor for the parent type.
Could perhaps be combined with active patterns?

## Response ##
** by fslang-admin on 7/18/2015 12:00:00 AM **

Many thanks for this suggestion. It is being marked as declined – for discussion see the comments.
Further discussion welcome
Don Syme, F# Language and Core Library Evolution.

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/5663374)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-5663374-allow-private-constructors-on-du-cases.md#comments)

**Comment by laurentpayot** [comment]
Coming from an Elm/PureScript background, not having private constructors is weird. The links to the discussions are dead. Is there any resource available to understand why we cannot use private constructors in F#?

**Comment by pblasucci** [comment]
@laurentpayot you absolutely _can_ have private constructors. What you cannot do is _mix_ private and some be public. So, either every variant's constructor is exposed, or none of them are. This is generally a fine compromise between controlling access and the complexity of changing the compiler -- especially if you consider involving active patterns and/or shadowing function.

**Comment by laurentpayot** [comment]
@pblasucci Thanks for your quick answer, I’m glad to hear that.
I just found out the private constructor syntax in [a Scott Wlaschin gist](https://gist.github.com/swlaschin/54cfff886669ccab895a#file-constrainedtypesexamples-fsx-L28). I could not find it in the [F# DU docs](https://learn.microsoft.com/en-us/dotnet/fsharp/language-reference/discriminated-unions)...
