### ISSUE TITLE
Pure Functions - "pure" keyword

### ISSUE THREAD

**Issue by baronfel** [baronfel/fsharp-lang-suggestions-final#201]
# Pure Functions - "pure" keyword [5670335] #

**Submitted by Will Smith on 3/23/2014 12:00:00 AM**  
**116 votes on UserVoice prior to migration**  

I've been thinking about this one for a while.
At the moment, it's pretty easy to make a pure function and as a long as you follow a few rules, you should be fine. There is just no guarantee. A way for the F# compiler to enforce a function to be "pure" and not allow any side effects/mutations ever would ensure that guarantee. A "pure" function will have more constraints. This may also allow for more aggressive optimizations.
A challenge with this is how do we handle existing functions that are referentially transparent and types that we know are immutable. My best shot at this is only allow the F# compiler to make exceptions to functions/types to be allowed in "pure" functions. An example would be the "string" type and its functions.

## Response ##
** by fslang-admin on 2/3/2016 12:00:00 AM **

Declining per my comment of July 18, 2015 12:16
Don Syme, F# Language Evolution

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/5670335)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-5670335-pure-functions-pure-keyword.md#comments)

**Comment by ShalokShalom** [comment]
@kspeakman Isaac writes about this [here](https://www.compositional-it.com/news-blog/impure-functions-in-fsharp/)

By the way: The links to the response of Don dont work anymore.

**Comment by kspeakman** [comment]
@ShalokShalom The article just says to use behavior testing. That's not the same as warnings from tooling. An example of which would be mutable variables, which are loudly highlighted in VS2019. I'm satisfied that more comprehensive tooling to warn about side effects is impractical in the .NET ecosystem, and practices have to pick up where tooling leaves off. We've worked out a balance and I'm okay with the trade-off.

**Comment by charlesroddie** [comment]
This C#/dotnet discussion is here: https://github.com/dotnet/csharplang/discussions/776
An F# implementation would be dependent on that. Without annotation across dotnet, the feature is not very useful as the compiler would not be able to infer purity when dotnet methods are used. Conversely if this is done in dotnet then F# would certainly support it.
