### ISSUE TITLE
Improve support for managed pointers (as in C# unsafe code)

### ISSUE THREAD

**Issue by baronfel** [baronfel/fsharp-lang-suggestions-final#202]
# Improve support for managed pointers (as in C# unsafe code) [5670437] #

**Submitted by Jack Pappas on 3/23/2014 12:00:00 AM**  
**33 votes on UserVoice prior to migration**  

It is currently quite difficult in F# to interoperate with 'unsafe' C# code due to C#'s use of managed pointers (ilsigptr<'T> in F#). At the very least, it would be handy to have a ManagedPtr module available in FSharp.Core under the Microsoft.FSharp.NativeInterop namespace, similar to the existing NativePtr module.
If support for managed pointers were to be improved, it would be beneficial to rename them -- ilsigptr<'T> is a rather obscure name for those without a good understanding of IL and the CLR's type system. Perhaps we could rename it to managedptr<'T>, which would fit nicely alongside the existing nativeptr<'T>.
Improved support for managed pointers would also go hand-in-hand with support for 'fixed'-bound variables: /archive/suggestion-5663721-add-support-for-fixed
When using the (&&) operator, and the * modifier in external function signatures, the F# compiler infers the types as nativeptr<'T>; I think it would be preferable if the compiler inferred these as managedptr<'T> instead, for better type safety when interoperating with other languages (e.g., C#). This could be implemented as the new default behavior in a future version of F#, and anyone relying on the nativeptr<'T> behavior could turn it back on using a compiler flag (e.g., --prefer-nativeptrs).

## Response ##
** by fslang-admin on 2/4/2016 12:00:00 AM **

Marking as declined pending an example where this is needed

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/5670437)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-5670437-improve-support-for-managed-pointers-as-in-c-un.md#comments)

**Comment by realvictorprm** [comment]
@Barone What isn't possible in the current state?
