### ISSUE TITLE
Easier to copy data between records of different types.

### ISSUE THREAD

**Issue by baronfel** [baronfel/fsharp-lang-suggestions-final#291]
# Easier to copy data between records of different types. [6124011] #

**Submitted by Matthew Moloney on 7/1/2014 12:00:00 AM**  
**32 votes on UserVoice prior to migration**  

Large data projects require lots of records with 100+ fields. These records require small changes over time, e.g. a new field is added. To update the data the old records are read in and copied to the new record field by field. The proposal is to automatically copy fields from an old record of type A to a new record of Type B where both the field names and the field types match.
type A = {x : int}
type B = {x : int; y : int}
let a : A = {x = 1}
let b : B = {a with y = 2}

## Response ##
** by fslang-admin on 2/3/2016 12:00:00 AM **

Closing in favor of /archive/suggestion-5663704-copy-and-update-on-class-types

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/6124011)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-6124011-easier-to-copy-data-between-records-of-different.md#comments)

**Comment by Lanayx** [comment]
@baronfel Hey, I'm interested in this feature, can you remember why it was closed?

**Comment by baronfel** [comment]
It's got the declined tag, so my guess is that @dsyme vetoed the suggestion back when we were on user voice.

I believe there may be another suggestion on this repo that is approved, by my searching isn't finding anything.

**Comment by Lanayx** [comment]
I've [found the link](https://github.com/fsharp/fslang-suggestions/blob/d48c35ce216e2bff148937ec028ad61e5c273fdf/archive/suggestion-5663704-copy-and-update-on-class-types-and-on-records-of.md) and couldn't find any negative comments that could lead to decline, maybe we can reopen this suggestion?

**Comment by jl0pd** [comment]
It doesn't seem to be necessary, since F# now have anonymous records and type aliases to anonymous records:
```fsharp
type A = {| a: int |}
type B = {| a: int; b: int |}

let a : A = {| a = 5 |}
let b : B = {| a with b = 7 |}

printfn "%A" b // prints { a = 5; b = 7 }
```

Although anonymous records fragile, when we're talking about library development, as they may change they're name. It's important for cases when new `dll` replaces old one in `bin` directory without recompilation.

**Comment by Lanayx** [comment]
@jl0pd thanks, I'm aware that you can do this with anonymous records, but this is not something we use in business code. Regular business code contains hundreds of records with dozens of fields in them, all with specific meaning, also hundreds of functions accepting those records, so using anonymous records is usually not a good choice there. Instead I need a simple way to copy packs of fields from one known record to another to reduce routine work and code size.
Probably I need to just create another issue and reference this :)
