### ISSUE TITLE
Generate curried creation functions for records

### ISSUE THREAD

**Issue by baronfel** [baronfel/fsharp-lang-suggestions-final#307]
# Generate curried creation functions for records [6257366] #

**Submitted by David Tchepak on 8/4/2014 12:00:00 AM**  
**7 votes on UserVoice prior to migration**  

This suggestion is along the lines of [1], but for records.
[1]: /archive/suggestion-5663317-allow-to-use-class-constructors-as-functions
It can be handy to have curried creation functions for records.
Say we have a record with a categoryId:
type Product = { categoryId : int; id : int; name : string }
And we want to create a number of records with the same categoryId. If we have a curried creation method we could do something like:
> type Product with static member create c i n = { categoryId = c; id = i; name = n };;
> let createPl = Product.create 432;;
val createPl : (int -> string -> Product)
> createPl 27 "F#", createPl 42 "Haskell", createPl 123 "C#";;
It would be great to have the compiler generate this. I don't really have a preference for the syntax (create a function with same name as type? So in this case we'd also get a function `Product : int -> int -> string`?)

## Response ##
** by fslang-admin on 9/16/2014 12:00:00 AM **

I’m declining this particular suggestion because of the comment below – “It seems the natural thing in F# would be to allow the record type name to be used as an uncurried constructor allowing named arguments…”
I will open a new suggestion for this.
Don Syme
Current BDFL F# Language/Library Evolution

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/6257366)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-6257366-generate-curried-creation-functions-for-records.md#comments)

**Comment by kspeakman** [comment]
I use this feature (curried constructors) in Elm, and it is sorely missed in F#. I find myself using type extensions to make curried constructor functions which requires annoying boilerplate.

```fsharp
type MyRecord = 
    { A : string 
      B : int 
      C : bool } 
    with 
        static member mk a b c = 
            { A = a 
              B = b 
              C = c }

... 
|> Result.map (MyRecord.mk someA someB)
```

Changes to the class require changing the boilerplate in two places (method declaration and body).

It would be great to recover that wasted time by having F# auto generate a curried constructor. I wish you would reconsider this feature.

(first added this comment to use voice before realizing it was no longer used)

**Comment by kspeakman** [comment]
Adding another example I commonly use with a validation pattern:

```fsharp
// I have to create this elementary constructor function every time
let courseCreated courseCode courseName description requiresProctor isActive : CourseCreated=
    {
        CourseCode = courseCode
        CourseName = courseName
        Description = description
        RequiresProctor = requiresProctor
        IsActive = isActive
    }

let create (cmd : CreateCourse) =
    Ok courseCreated
        |> verify (Ensure.nonBlank CodeBlank cmd.CourseCode)
        |> verify (Ensure.nonBlank NameBlank cmd.CourseName)
        |> verify (Ensure.noneOr (Ensure.nonBlank DescriptionInvalid) cmd.Description)
        |> verify (Ok cmd.RequiresProctor)
        |> verify (Ok cmd.IsActive)
```

I can't find the other issue, but I recall @dsyme saying that it would be problematic for making field order significant. But field order is already significant in the generated tupled constructor. This affects me when using an object mapper like Dapper... the `SELECT` order has to exactly match the field order. Sometimes I change the field order on the record, and sometimes it makes more sense to change the `SELECT` order. Either way, this is already a faced issue so it would not be any different for curried constructors.

I use the same functionality from Elm all the time (in which field order is also significant), and I really miss it when I switch to F# the back-end.
