### ISSUE TITLE
Aliases for namespaces

### ISSUE THREAD

**Issue by baronfel** [baronfel/fsharp-lang-suggestions-final#310]
# Aliases for namespaces [6323201] #

**Submitted by Daniel Bradley on 8/20/2014 12:00:00 AM**  
**17 votes on UserVoice prior to migration**  

[ Edited by admin to apply to namespaces only, since as per comment you can already do this with module aliases ]
When using the ‘open’ keyword, allow a namespace being imported, to be assigned to an alias rather than the imported contents being made available to the current scope e.g.
namespace Foo = Some.Long.Path.To.Foo
This would be useful when importing namespaces containing modules/types with the same name to avoid fully qualifying all of the usages.

## Response ##
** by fslang-admin on 2/10/2016 12:00:00 AM **

Thanks for the suggestion. It is quite a reasonable one and it has taken me a long time to mark this as declined. However I have now done so for the reasons listed below.
Don Syme, F# Language Evolution

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/6323201)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-6323201-aliases-for-namespaces.md#comments)

**Comment by toraritte** [comment]
Would anyone provide a short summary why this was declined? Both links above are broken and they were also never archived in Internet Archive. Thank you!

**Comment by smoothdeveloper** [comment]
@toraritte https://github.com/fsharp/fslang-suggestions/blob/d48c35ce216e2bff148937ec028ad61e5c273fdf/archive/suggestion-6323201-aliases-for-namespaces.md

if you browse this repository root, and check "[View all archived uservoice suggestions and comments](https://github.com/fsharp/fslang-suggestions/tree/d48c35ce216e2bff148937ec028ad61e5c273fdf/archive)" link, you'll be able to find most of the contents, despite it is not the most convenient, it is still there.
