### ISSUE TITLE
Add "lengthBy" function to Seq/Array/List

### ISSUE THREAD

**Issue by baronfel** [baronfel/fsharp-lang-suggestions-final#329]
# Add "lengthBy" function to Seq/Array/List [6466039] #

**Submitted by Patrick Q on 9/21/2014 12:00:00 AM**  
**7 votes on UserVoice prior to migration**  

Currently there is no function that returns a number representing how many elements in a specified collection satisfies a condition.
For instance consider what we need to do to count the number of odd numbers in a list:
let numbers = [ 5; 4; 1; 3; 9; 8; 6; 7; 2; 0 ]
let oddsCount = numbers |> List.filter (fun n -> n % 2 = 1) |> List.length
It would be much more efficient and convenient to have a lengthBy function to allow the following:
let oddsCount = numbers |> List.lengthBy (fun n -> n % 2 = 1)
Getting a count based on a predicate is such a fundamental operation that I believe there should be a single dedicated function. In C# for instance there is an overload for the Count method that provides this functionality and it's equivalent absence in F# appears to be a bit of an oversight.

## Response ##
** by fslang-admin on 10/15/2014 12:00:00 AM **

I’m marking this as declined since it is not included in the F# 4.0 FSharp.Core design. However please feel free to continue the discussion.
Don Syme

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/6466039)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-6466039-add-lengthby-function-to-seq-array-list.md#comments)

**Comment by theprash** [comment]
I would call this function `countIf` or `countWhen`.

**Comment by jackfoxy** [comment]
filteredLength

**Comment by Tarmil** [comment]
Or `countWhere`, which would be consistent with the existing `where` synonym for `filter`.

**Comment by Happypig375** [comment]
Can we just call this `count`?

**Comment by jackfoxy** [comment]
Agree, anything with "length" in it is the wrong name for this otherwise useful suggestion. I like `countWhere`.
