### ISSUE TITLE
Parameterized and First Class Modules

### ISSUE THREAD

**Issue by baronfel** [baronfel/fsharp-lang-suggestions-final#351]
# Parameterized and First Class Modules [6603685] #

**Submitted by Jared Hester on 10/23/2014 12:00:00 AM**  
**55 votes on UserVoice prior to migration**  

Extend the F# module system to allow paramaterization via functors (that's why the keyword is reserved right?)
First class modules where a module declared with an abbreviation/alias is equal to a module declared with the original module name (unlike OCaml)
It seems like a more robust module system would provide a functional alternative to MEF with a cleaner abstraction model.
Perhaps the `pure` keyword could be used in conjunction with `functor` to enforce a restraint against immutability to ensure the functor is applicative?
See "F-ing modules"
http://www.mpi-sws.org/~rossberg/papers/Rossberg,%20Russo,%20Dreyer%20-%20F-ing%20Modules%20%5BJFP%20Draft%5D.pdf

## Response ##
** by fslang-admin on 2/4/2016 12:00:00 AM **

Declining per my comment below,
Don Syme, F# Language Evolution

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/6603685)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-6603685-parameterized-and-first-class-modules.md#comments)

**Comment by dsyme** [comment]
Notes from F# Language Design Office Hours:

> The original request was here: https://fslang.uservoice.com/forums/245727-f-language/suggestions/6603685 and contains a record of my thoughts.  
> 
> That said, people still ask for this.  However it's not entirely clear what they are asking for and a lot rides on this.  For example, can the static members of types in a module access the enclosing parameters?
> 
> ```fsharp
> module M(x:int) = 
>     type X =
>         | A of int
>         | B of int
>         static member Q() = x + x
> ```
> 
> In that case, hidden-parameter passing of the module parameters would be the only viable implementation technique.  This is one of the reasons that the original F# object programming design didn't include nested types - or if we did we would likely use the syntax
> 
> ```fsharp
> type C(x:int) =
>    static type X = ....
> ```
> 
> to indicate that the type X doesn't have access to the enclosing instance parameters.  That is reasonable enough to people familiar with .NET object programming, but will look odd in a system of paramaterized modules. Also, the other points made in the link above do still apply.
> 
> (In office hours, don't take everything I say as gospel... it's an informal session to get us all thinking....)

**Comment by baronfel** [comment]
I updated this link, I don't know if/when I'll have time to look into the overall problem
