### ISSUE TITLE
Implement types within types

### ISSUE THREAD

**Issue by baronfel** [baronfel/fsharp-lang-suggestions-final#380]
# Implement types within types [6909164] #

**Submitted by Alexander Baggett on 1/1/2015 12:00:00 AM**  
**4 votes on UserVoice prior to migration**  

It would look something like this
type Music() =
type Note() =
static member x = 10
static member sixteenth = 40

## Response ##
** by fslang-admin on 1/23/2015 12:00:00 AM **

Duplicate, /archive/suggestion-6085086-nested-types-for-f

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/6909164)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-6909164-implement-types-within-types.md#comments)

**Comment by panesofglass** [comment]
Does anyone know why this was declined?

**Comment by cartermp** [comment]
Neither the duplicate nor the original give a reason, so I guess it is: @dsyme doesn't want nested types in the language at this time :)

**Comment by dsyme** [comment]
I'm ok with adding nested type definitions to F# at this stage in its evolution and now some other issues like `namespace rec` have been sorted out.

I'll mark https://github.com/fsharp/fslang-suggestions/issues/277 as approved in principle.
