### ISSUE TITLE
Indentation of new lines should be dependent on the *start* of the previous line, not the end of it

### ISSUE THREAD

**Issue by baronfel** [baronfel/fsharp-lang-suggestions-final#433]
# Indentation of new lines should be dependent on the *start* of the previous line, not the end of it [7813977] #

**Submitted by George on 5/4/2015 12:00:00 AM**  
**10 votes on UserVoice prior to migration**  

The following layout requires that content after the 'View<' be indented beyond the endding '<' on the following lines which makes the level of indentation dependent on the type name. Which is silly.
[<AbstractClass>]
type View<
'Events,
'Window when
'Window :> Window and
'Window : (new : unit -> 'Window)
>(?window) =
let window = defaultArg window (new 'Window())
member this.Window = window

## Response ##
** by fslang-admin on 2/3/2016 12:00:00 AM **

Closing in favour of /archive/suggestion-9156844-relax-some-of-the-indentation-rules and linking back here

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/7813977)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-7813977-indentation-of-new-lines-should-be-dependent-on-t.md#comments)

**Comment by smoothdeveloper** [comment]
This was closed in favor of #470
