### ISSUE TITLE
Compiler Plugins like Rust

### ISSUE THREAD

**Issue by baronfel** [baronfel/fsharp-lang-suggestions-final#477]
# Compiler Plugins like Rust [9451143] #

**Submitted by Jared Hester on 8/23/2015 12:00:00 AM**  
**59 votes on UserVoice prior to migration**  

In Rust compiler plugins are user created libraries that can extend syntax behavior with new syntax extensions, lint checks, etc.
A compiler plugin system would enable a laboratory of experimentation with language features, giving them the potential to prove themselves trough implementation and application. There are definitely some language features that people have requested that may not seem like a worthwhile investment of resources due to their lack of relevance to a broad spectrum of users, but a compiler plugin system could remove that roadblock from their path toward reification.
A compiler plugin system facilitates a marketplace of ideas. The interchange of approaches, goals, pitfalls and adaptations will distill the best augmentations to the point where they might even be worthy of being incorporated as a part of the core language.
http://smallcultfollowing.com/rust-int-variations/imem-umem/guide-plugin.html

## Response ##
** by fslang-admin on 2/4/2016 12:00:00 AM **

Declining per my comment below: right now this is best registered as an FSharp.Cpmpiler.Service feature request.
Don Syme, F# Language Evolution

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/9451143)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-9451143-compiler-plugins-like-rust.md#comments)

**Comment by sighoya** [comment]
Why it was declined?

**Comment by sighoya** [comment]
FSharp.Cpmpiler.Service is nice, but it is something separate
I like the way in haskell to plugin language extensions by:
{-# LANGUAGE <Extension>, <Extension> #-}
rather than to create an extra F# compiler.
My question is, despite it was declined, is there a probability that the standard F# compiler will be shipped some day with compiler plugin support?

**Comment by vasily-kirichenko** [comment]
@sighoya No.

**Comment by sighoya** [comment]
Why?

**Comment by vasily-kirichenko** [comment]
No resources. Unless somebody (like you) implements it, of course.

**Comment by sighoya** [comment]
aaaah, okay, thats a statement
Thanks!

**Comment by codingedgar** [comment]
Is this still out of question?

**Comment by codingedgar** [comment]
The link of the response is broken, but this one works:

https://github.com/fsharp/fslang-suggestions/blob/d48c35ce216e2bff148937ec028ad61e5c273fdf/archive/suggestion-9451143-compiler-plugins-like-rust.md

**Comment by cartermp** [comment]
No plans to allow compiler plugins in F#, no.

**Comment by codingedgar** [comment]
@cartermp if it is not much to ask, could you elaborate on why not? (just for insight)

**Comment by cartermp** [comment]
It's just not something we're interested in pursuing. It's an extremely high-cost feature without a terrible amount of use for everyday F# programming.

**Comment by codingedgar** [comment]
@cartermp Thank you 💛
