### ISSUE TITLE
Add Result<'Success,'Failure> to FSharp.Core

### ISSUE THREAD

**Issue by baronfel** [baronfel/fsharp-lang-suggestions-final#479]
# Add Result<'Success,'Failure> to FSharp.Core [9484395] #

**Submitted by Oskar Gewalli on 8/25/2015 12:00:00 AM**  
**17 votes on UserVoice prior to migration**  

In order to be able to write code that you can easily consume that does not throw an exception have a fsharp core type with the following signature:
type Result<'TSuccess,'TError> =
| Success of 'TSuccess
| Error of 'TError
from
https://github.com/fsharp/fsharp/issues/479

## Response ##
** by fslang-admin on 8/2/2016 12:00:00 AM **

Completed. The RFC is here: https://github.com/fsharp/FSharpLangDesign/blob/master/RFCs/FS-1004-result-type.md
Don Syme
F# Language and Core Library Evolution

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/9484395)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-9484395-add-result-success,-failure-to-fsharp-core.md#comments)

**Comment by ShalokShalom** [comment]
The link to the RFC changed: https://github.com/fsharp/fslang-design/blob/main/FSharp-4.1/FS-1004-result-type.md

(might wanna edit this in the original post)
